title: <p align="center"> Deepak Panwar </p>
logo: /assets/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="www.linkedin.com/in/deepak-panwar-0240b173">LinkedIn</a>
  <a href="https://github.com/deepak3952">GitHub</a>
  
  <br>   
  I' am working as a data scientis in boeing
  Working on ML and AI applications.
  <br>
  </p>



theme: jekyll-theme-minimal
